create table if not exists public.matchups (
  id bigint generated by default as identity primary key,
  pool text not null,
  matchup_id text not null,
  stage text not null,
  conference text not null,
  round_label text,
  matchup_type text not null default 'series',
  team_a text not null,
  team_b text not null,
  starts_at timestamptz null,
  actual_winner text null,
  actual_score_a int null,
  actual_score_b int null,
  sort_order bigint null default 0,
  created_at timestamptz not null default now(),
  unique(pool, matchup_id)
);
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  pool text not null,
  matchup_id text not null,
  game_no int not null,
  label text,
  team_a text not null,
  team_b text not null,
  starts_at timestamptz null,
  actual_winner text null,
  score_a int null,
  score_b int null,
  created_at timestamptz not null default now(),
  unique(pool, matchup_id, game_no),
  constraint games_matchup_fk foreign key (pool, matchup_id) references public.matchups(pool, matchup_id) on delete cascade
);
create table if not exists public.series_picks (
  id bigint generated by default as identity primary key,
  pool text not null,
  matchup_id text not null,
  nickname text not null,
  picked_winner text not null,
  picked_score_a int null,
  picked_score_b int null,
  created_at timestamptz not null default now(),
  unique(pool, matchup_id, nickname),
  constraint series_picks_matchup_fk foreign key (pool, matchup_id) references public.matchups(pool, matchup_id) on delete cascade
);
create table if not exists public.game_picks (
  id bigint generated by default as identity primary key,
  pool text not null,
  game_id bigint not null,
  nickname text not null,
  picked_winner text not null,
  created_at timestamptz not null default now(),
  unique(pool, game_id, nickname),
  constraint game_picks_game_fk foreign key (game_id) references public.games(id) on delete cascade
);
alter table public.matchups add column if not exists actual_winner text null;
alter table public.matchups add column if not exists actual_score_a int null;
alter table public.matchups add column if not exists actual_score_b int null;
alter table public.matchups add column if not exists sort_order bigint null default 0;
alter table public.games add column if not exists actual_winner text null;
alter table public.games add column if not exists score_a int null;
alter table public.games add column if not exists score_b int null;
alter table public.games add column if not exists starts_at timestamptz null;
alter table public.series_picks add column if not exists picked_score_a int null;
alter table public.series_picks add column if not exists picked_score_b int null;
alter table public.matchups enable row level security;
alter table public.games enable row level security;
alter table public.series_picks enable row level security;
alter table public.game_picks enable row level security;
drop policy if exists "matchups open" on public.matchups;
drop policy if exists "games open" on public.games;
drop policy if exists "series picks open" on public.series_picks;
drop policy if exists "game picks open" on public.game_picks;
create policy "matchups open" on public.matchups for all using (true) with check (true);
create policy "games open" on public.games for all using (true) with check (true);
create policy "series picks open" on public.series_picks for all using (true) with check (true);
create policy "game picks open" on public.game_picks for all using (true) with check (true);
